# Generated by Django 2.0.6 on 2018-11-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=50)),
                ('Title', models.CharField(max_length=50)),
                ('Location', models.CharField(max_length=50)),
                ('P_Language', models.CharField(max_length=50)),
                ('Github', models.CharField(max_length=300)),
                ('Level', models.CharField(max_length=100)),
            ],
        ),
    ]
